### ISSUE TITLE
CPU human names cannot consist only of numeric characters

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#22]
When a CPU human name consists only of numeric characters and spaces the application fails to load properly. The background and tabs will be drawn but none of the database's contents will be displayed. This will not cause any issue when compiling only in the display.

**Comment by markasoftware** [comment]
Generally speaking, I don't think any parts should consist of only numeric characters, but this is still a bug and will be fixed soon.

**Comment by markasoftware** [comment]
Actually, I am going to close this issue without fixing it, because it only really makes sense for a name to be a string -- a numerical name doesn't make much sense, since doing arithmetic operations on a name is meaningless. You can force YAML to treat a number as a string by enclosing it with quotes (e.g, `humanName: '123'`), which is how a name which is a number should be dealt with.
